server:
  port: 9093
spring:
  datasource:
    url: jdbc:h2:mem:order_item
    username: order_item
    password: order_item
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  application:
    name: "ORDER-API"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka